{% set version = "0.23.20" %}


package:
  name: p11-kit
  version: {{ version }}

source:
  url: https://github.com/p11-glue/p11-kit/releases/download/{{ version }}/p11-kit-{{ version }}.tar.xz
  sha256: 14d86024c3dfd6b967d9bc0b4ec7b2973014fe7423481f4d230a1a63b8aa6104

build:
  number: 0
  # Windows: libtasn1 not available
  # OSX: libtasn1 not found despite dependency: 
  # https://travis-ci.org/conda-forge/staged-recipes/builds/440551277#L564
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libffi
    - libtasn1
  run:
    - libffi
    - libtasn1

test:
  commands:
    - p11-kit -h

about:
  home: https://github.com/p11-glue/p11-kit
  license: MIT
  license_file: COPYING
  summary: Provides a way to load and enumerate PKCS#11 modules

extra:
  recipe-maintainers:
    - chapmanb
    - marcelotrevisani
